### ISSUE TITLE
Crashes on 1.18.2

### ISSUE THREAD

**Issue by PweSol** [Ladysnake/Illuminations#119]
Crashing even without other mods.

**Comment by North-West-Wind** [comment]
I made a [fork](https://github.com/North-West-Wind/Illuminations)
You can try building it from there

**Comment by yuri0r** [comment]
do i see right that the fix is mostly refactoring 
colorRed, colorGreen & colorBlue to red, green & blue respectivly? thats curios.

**Comment by North-West-Wind** [comment]
Well yes, and some parameter and method call changes in getBiome and ClientWorldMixin
The refactoring is because I changed the mapping to 1.18.2

**Comment by Dragonisser** [comment]
> do i see right that the fix is mostly refactoring colorRed, colorGreen & colorBlue to red, green & blue respectivly? thats curios.

Leaves me wondered why there hasn't been any official fix yet. That cant take long, 30min at max.

**Comment by Sunconure11** [comment]
@doctor4t

**Comment by Xiribidus** [comment]
rat is busy, he will go through the PRs/make an own update whenever he is ready

**Comment by Sunconure11** [comment]
Alright, was just seeing if he was willing to look now or not, since that worked with someone else... lol

**Comment by MarkinhosMLP** [comment]
same with me....


java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'illuminations'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_3494$class_5123
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_3494$class_5123
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 17 more

**Comment by North-West-Wind** [comment]
@MarkinhosMLP is that my fork or downloaded from curseforge?
