### ISSUE TITLE
Crashes on Vanilla Servers

### ISSUE THREAD

**Issue by Fioofyy** [Ladysnake/Illuminations#141]
Illuminations.data Null

Crashes when loading up any vanilla type server.

**Comment by Fioofyy** [comment]
Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "com.google.common.collect.ImmutableSet.iterator()" because "illuminationDataSet" is null
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2)
	at net.minecraft.client.world.ClientWorld.spawnParticles(ClientWorld:3652)
	at net.minecraft.client.world.ClientWorld.handler$bnc000$randomBlockDisplayTick(ClientWorld:3636)
	at net.minecraft.client.world.ClientWorld.randomBlockDisplayTick(ClientWorld:403)
	at net.minecraft.client.world.ClientWorld.doRandomBlockDisplayTicks(ClientWorld:358)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1854)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1101)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:734)
	at net.minecraft.client.main.Main.main(Main:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Berkouli** [comment]
I have the same problem, but for me it crashes when I go too far on my server.

**Comment by doctor4t** [comment]
Does this version seem to fix your issue?

[illuminations-1.10.7.jar.zip](https://github.com/Ladysnake/Illuminations/files/8970410/illuminations-1.10.7.jar.zip)

**Comment by Berkouli** [comment]
> Does this version seem to fix your issue?
> 
> [illuminations-1.10.7.jar.zip](https://github.com/Ladysnake/Illuminations/files/8970410/illuminations-1.10.7.jar.zip)

Just tested it, working fine!

**Comment by Fioofyy** [comment]
Yep! i can confirm that works.

**Comment by doctor4t** [comment]
> Yep! i can confirm that works.

Perfect, I'll then push a hotfix with this
