### ISSUE TITLE
Weirdness when trying to disable auto updates/Vanguard

### ISSUE THREAD

**Issue by Fourmisain** [Ladysnake/Illuminations#62]
(Disclaimer: This might actually be more related to [Vanguard](https://github.com/Ladysnake/Vanguard), but I'm looking at it through Illuminations' scope.)

It - the weirdness - is a bit complicated to explain, so I'll try to describe the exact happenings.

## First scenario

When I start out with just `illuminations-1.4.2.jar` and setting `auto-update=false` in `illuminations.properties`, I get the log message

> [Vanguard] [main/INFO]: Vanguard is looking for updates for illuminations

Also, `vanguard-uninstaller.jar` and a `vanguard.properties` with `toggle=true` is added.

I'm not sure if it actually checked for updates or if the log message is incorrect, both should be considered bugs.
I'm also not sure what the `toggle` means - I assume it's to enable/disable vanguard itself, because it is technically it's own mod?

## Second scenario

Following the first scenario, restarting Minecraft will produce the log
> [Vanguard] [main/INFO]: Vanguard is looking for updates for illuminations
> [net.minecraft.class_2983] [main/INFO]: [STDERR]: java.nio.file.AccessDeniedException: mods\vanguard-uninstaller.jar
> [net.minecraft.class_2983] [main/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89)
> [net.minecraft.class_2983] [main/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103)
> [net.minecraft.class_2983] [main/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:108)
> [net.minecraft.class_2983] [main/INFO]: [STDERR]: 	at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:274)
> [net.minecraft.class_2983] [main/INFO]: [STDERR]: 	at java.base/sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:110)
> [net.minecraft.class_2983] [main/INFO]: [STDERR]: 	at java.base/java.nio.file.Files.deleteIfExists(Files.java:1180)
> [net.minecraft.class_2983] [main/INFO]: [STDERR]: 	at java.base/java.nio.file.Files.copy(Files.java:3054)
> [net.minecraft.class_2983] [main/INFO]: [STDERR]: 	at ladysnake.vanguard.Vanguard.onInitialize(Vanguard.java:75)
> ...

Which looks like `vanguard-uninstaller.jar` is trying to uninstall itself while still being accessed.
That said, closing Minecraft does indeed delete `vanguard-uninstaller.jar`.

Nothing changes in the configuration, which means the next Minecraft start will be the first scenario again.
So it is in a constant state of adding and deleting `vanguard-uninstaller.jar`.

## Third and fourth scenarios

When I repeat the first two scenarios while setting `toggle=false` in `vanguard.properties`, nothing appears to change at all.

## Test using Illumination 1.4.1

I wanted to test if the update check actually happens.
So I installed just `illuminations-1.4.1.jar` while setting `auto-update=false` and `toggle=false`.

It produced the log
> [Vanguard] [main/INFO]: Vanguard is looking for updates for illuminations
> ...
> [Vanguard] [Thread-135/INFO]: Minecraft instance shutting down, starting mod uninstaller

**deleted** `illuminations-1.4.1.jar` and added `vanguard-uninstaller.jar`.

I see that vanguard [was patched](https://github.com/Ladysnake/Illuminations/commit/4b628c04708ba26e84443559a2129632f73a64ad) for just that:

> Fixed an issue with Vanguard that would cause Illuminations to remove itself

So this whole test turned out pretty pointless, didn't it?

## Conclusion

It is weird that `vanguard-uninstaller.jar` is being added and removed constantly while leaving worrying log messages.
It is also weird, that vanguard's `toggle` doesn't seem to do anything - it probably does but you just can't tell.

I'm not exactly sure what the purpose of `vanguard-uninstaller.jar` is, but I assume it is to uninstall old Illuminations versions.
If that's so, `vanguard-uninstaller.jar` should only be added if an update has actually been found and was downloaded/installed.

**Comment by doctor4t** [comment]
Posting this in the Vanguard issue would have been perfect, but this is a very good issue nonetheless. Thank you for the report, I'll have a look and deploy a fix asap.
